#!/usr/bin/env bash
#
# mayhem/build.sh — build the mimic1 text-to-speech FRONT-END fuzzer, a standalone reproducer,
# and (in a separate clean tree) the project's own unit-test binaries + the `t2p` CLI used as a
# known-answer oracle probe.
#
#   build-fuzz/.libs/*.a   sanitized static archives (libttsmimic + cmulex + usenglish)
#   t2p_synth_fuzzer            sanitized + libFuzzer   -> Mayhem target `t2p_synth_fuzzer`
#   t2p_synth_fuzzer-standalone sanitized, run-once      -> crash reproducer (no libFuzzer runtime)
#   build-tests/                NORMAL flags, `make check` + `make t2p` -> the upstream unit
#                                suite (cutest) and a clean, dynamically-linked `t2p` binary used
#                                by mayhem/test.sh as a KAT probe.
#
# mimic1 is an autotools (automake/libtool) project. Both trees are OUT-OF-TREE VPATH builds
# (`../configure` run from a build subdir) so the sanitized and clean builds can coexist without a
# `make clean` dance, and so re-running this script on an already-built tree (the offline/air-gap
# re-run) is safe: each tree is removed and rebuilt from scratch, never assumed pre-configured.
#
# Only the built-in "no_wave" US-English voice is built (usenglish text analysis + the CMU
# lexicon/letter-to-sound rules): `--disable-voices-all --without-hts` skips every compiled-in
# clustergen/diphone/hts voice (they need waveform synthesis, which this target deliberately
# never runs), so the build stays fast and needs no external voice/lexicon file at fuzz time.
set -euo pipefail

[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${MAYHEM_JOBS:=$(nproc)}"
# SanitizerCoverage for the WHOLE library, not just the harness TU — without it libFuzzer/Mayhem
# get no coverage feedback from the fuzzed code (0 edges). fuzzer-no-link instruments without
# hijacking main(). Appended unconditionally, even when $SANITIZER_FLAGS is empty.
FUZZ_COV="-fsanitize=fuzzer-no-link"
export SANITIZER_FLAGS DEBUG_FLAGS CC CXX LIB_FUZZING_ENGINE MAYHEM_JOBS

cd "${SRC:=/mayhem}"

# Common autotools configure flags: static archives only (so we link them into our own harness
# binary by hand), no audio backend (CST_AUDIO_NONE — the front end never touches audio), only
# the English lexicon/text-analysis language pack, no compiled-in voices, no HTS.
CONF_FLAGS=(
  --prefix=/usr --disable-shared --enable-static
  --with-audio=none
  --disable-voices-all
  --without-hts
  --disable-lang-indic
  --disable-lang-es
)

# `./configure` (generated by autogen.sh) MUST NOT be run in $SRC itself: both VPATH build trees
# below configure straight from the source dir, and autoconf refuses that if $SRC is *also*
# configured ("source directory already configured; run make distclean there first"). Only
# (re)generate the `configure` script in-tree; never `./configure` in $SRC.
if [ ! -x configure ] || [ -f Makefile ]; then
  [ -f Makefile ] && make distclean >/dev/null 2>&1 || true
  ./autogen.sh
fi

# ── 1) Sanitized build of the library, out-of-tree, static archives only ──────────────────────
rm -rf build-fuzz
mkdir -p build-fuzz
(
  cd build-fuzz
  ../configure "${CONF_FLAGS[@]}" CC="$CC" CXX="$CXX"
  # `t2p` pulls in exactly the three libraries the harness needs (libttsmimic, cmulex,
  # usenglish); building it is the simplest way to get all three sanitized .a archives without
  # hand-listing their object files. -Wno-error cancels the project's AM_CPPFLAGS `-Werror`
  # (order: AM_CPPFLAGS comes first, so a later user CPPFLAGS wins) — new clang/sanitizer
  # warnings on 20+ year old C must not fail this build; ASan/UBSan diagnostics still HALT.
  make -j"$MAYHEM_JOBS" t2p \
    CFLAGS="$SANITIZER_FLAGS $FUZZ_COV $DEBUG_FLAGS" \
    CPPFLAGS="-Wno-error"
)

FUZZ_LIBS=(
  build-fuzz/.libs/libttsmimic_lang_cmulex.a
  build-fuzz/.libs/libttsmimic_lang_usenglish.a
  build-fuzz/.libs/libttsmimic.a
)
FUZZ_INCS=(-Ibuild-fuzz/include -Iinclude -Ilang/usenglish -Ilang/cmulex)

# ── 2) Harness: fuzzer binary + standalone reproducer (sanitized, DWARF < 4) ──────────────────
# --start-group/--end-group: these three static archives are mutually referential (usenglish and
# cmulex both call back into libttsmimic), and a single left-to-right archive scan leaves symbols
# unresolved depending on order; grouping makes ld re-scan until everything resolves (the same
# thing libtool's own link line achieves for `t2p` via its .la dependency metadata).
$CC $SANITIZER_FLAGS $FUZZ_COV $DEBUG_FLAGS "${FUZZ_INCS[@]}" $LIB_FUZZING_ENGINE \
  mayhem/t2p_synth_fuzzer.c \
  -Wl,--start-group "${FUZZ_LIBS[@]}" -Wl,--end-group \
  -lm -lpcre2-8 \
  -o t2p_synth_fuzzer

$CC $SANITIZER_FLAGS $DEBUG_FLAGS "${FUZZ_INCS[@]}" "$STANDALONE_FUZZ_MAIN" \
  mayhem/t2p_synth_fuzzer.c \
  -Wl,--start-group "${FUZZ_LIBS[@]}" -Wl,--end-group \
  -lm -lpcre2-8 \
  -o t2p_synth_fuzzer-standalone

test -x t2p_synth_fuzzer
test -x t2p_synth_fuzzer-standalone

# ── 3) The project's OWN test suite + a clean `t2p`, NORMAL flags (independent of the sanitized
#        build above) ── mayhem/test.sh only RUNS these, never compiles.
rm -rf build-tests
mkdir -p build-tests
(
  cd build-tests
  ../configure "${CONF_FLAGS[@]}" CC="$CC" CXX="$CXX"
  # Two SEPARATE make invocations, not `make check t2p` in one call: automake's recursive-make
  # spawns one sub-make PER GOAL when given multiple targets, and two sub-makes building the
  # same objdir in parallel race on the same .deps/*.Tpo temp files (`mv: cannot stat ...Tpo`).
  make -j"$MAYHEM_JOBS" check CPPFLAGS="-Wno-error"
  make -j"$MAYHEM_JOBS" t2p CPPFLAGS="-Wno-error"
)

test -x build-tests/t2p
test -x build-tests/unittests/hrg_test

echo "build.sh: built /mayhem/t2p_synth_fuzzer (+ -standalone) and the clean build-tests/ oracle tree"
